In [29]:
import torch
import numpy
import torch.nn as nn
import torch.nn.functional as F

#word embedding
#source sentence and target sentence
#构建序列 序列的字符以索引的形式
batch_size = 2
#单词表大小
max_num_src_words = 8
max_num_tgt_words = 8

model_dim = 8 #特征大小 原来论文是512

#最大序列长度
max_src_seq_len = 5
max_tgt_seq_len = 5



max_position_len = 5
# src_len = torch.randint(2, 5, (batch_size, ))
# tgt_len = torch.randint(2, 5, (batch_size, ))
src_len = torch.Tensor([2, 4]).to(torch.int32) #两个句子 每个句子的长度
tgt_len = torch.Tensor([4, 3]).to(torch.int32)

#单词索引构成的句子 
#源序列目标索引 句子的每个单词在单词字典索引当中的位置
src_seq = torch.cat([torch.unsqueeze(F.pad(torch.randint(1, max_num_src_words, (L,)), (0, max_src_seq_len - L)), 0) \
                     for L in src_len])

#目标序列目标索引
tgt_seq = torch.cat([torch.unsqueeze(F.pad(torch.randint(1, max_num_tgt_words, (L,)), (0, max_tgt_seq_len - L) ), 0) \
                    for L in tgt_len])


#构造embedding  +1是因为最少填充了一行

src_embedding_table = nn.Embedding(max_num_src_words+1, model_dim)
tgt_embedding_table = nn.Embedding(max_num_tgt_words + 1, model_dim)


src_embedding = src_embedding_table(src_seq)
tgt_embedding = tgt_embedding_table(tgt_seq)


#构造position embedding 先统一计算公式里面的
pos_mat = torch.arange(max_position_len).reshape(-1, 1)
i_mat = torch.pow(10000, torch.arange(0, 8, 2).reshape((1,-1)) / model_dim )
#PE是两个维度 position和dim
pe_embedding_table = torch.zeros(max_position_len, model_dim)
pe_embedding_table[:, 0::2] = torch.sin(pos_mat / i_mat)
pe_embedding_table[:, 1::2] = torch.cos(pos_mat / i_mat)
print(pe_embedding_table)


pe_embedding = nn.Embedding(max_position_len, model_dim)
pe_embedding.weight = nn.Parameter(pe_embedding_table, requires_grad=False)

#位置的索引
# src_pos = torch.tensor([torch.arange(max(src_len)) for _ in src_len]).to(torch.int32)
# tgt_pos = torch.tensor([torch.arange(max(tgt_len)) for _ in tgt_len]).to(torch.int32)
src_pos = torch.cat([torch.unsqueeze(torch.arange(max(src_len)), 0) for _ in src_len]).to(torch.int32)
tgt_pos = torch.cat([torch.unsqueeze(torch.arange(max(tgt_len)), 0) for _ in tgt_len]).to(torch.int32)


src_pe_embedding = pe_embedding(src_pos)
tgt_pe_embedding = pe_embedding(tgt_pos)


# print(src_pe_embedding)
# print(tgt_pe_embedding)
# print(pe_embedding_table)

# print(src_seq.shape)
# print(src_embedding.shape)


# print(src_embedding)
# print(tgt_embedding)

# print(src_len)
# print(tgt_len)

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
          9.9995e-01,  1.0000e-03,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
          9.9980e-01,  2.0000e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
          9.9955e-01,  3.0000e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  3.8942e-01,  9.2106e-01,  3.9989e-02,
          9.9920e-01,  4.0000e-03,  9.9999e-01]])
tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
           1.0000e+00,  0.0000e+00,  1.0000e+00],
         [ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
           9.9995e-01,  1.0000e-03,  1.0000e+00],
         [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
           9.9980e-01,  2.0000e-03,  1.0000e+00],
         

In [34]:
alpha1 = 0.1
alpha2 = 10
score = torch.randn(5)
prob1 = F.softmax(score * alpha1, -1)
prob2 = F.softmax(score * alpha2, -1)
print(prob1)
print(prob2)

tensor([0.1861, 0.1916, 0.2003, 0.2280, 0.1939])
tensor([1.5520e-09, 2.8970e-08, 2.4636e-06, 1.0000e+00, 9.5136e-08])
