In [5]:
import torch
import torch.nn as nn
import torch.functional as F
from torch.utils.data import Dataset, DataLoader

In [8]:
class MyDataloader(Dataset):
    def __init__(self, data):
        self.data = data
    
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self,idx):
        return self.data[idx]


In [12]:
import numpy
l = numpy.random.rand(8,2)
loader = DataLoader(MyDataloader(l), batch_size=2, shuffle=True)
print(l)
for batch in loader:
    print(batch)

[[0.09127078 0.4999268 ]
 [0.49922849 0.00663025]
 [0.53628351 0.20880711]
 [0.4339119  0.1384567 ]
 [0.26241986 0.54903677]
 [0.00808484 0.44801729]
 [0.22049767 0.65857522]
 [0.24128505 0.9263884 ]]
tensor([[0.0913, 0.4999],
        [0.4992, 0.0066]], dtype=torch.float64)
tensor([[0.5363, 0.2088],
        [0.4339, 0.1385]], dtype=torch.float64)
tensor([[0.2624, 0.5490],
        [0.0081, 0.4480]], dtype=torch.float64)
tensor([[0.2205, 0.6586],
        [0.2413, 0.9264]], dtype=torch.float64)


In [32]:
t = torch.arange(1,6)
print(t)
# x = t.unsqueeze(1)
z =  torch.arange(2,5,2)
print(z)
print(x / z)

tensor([1, 2, 3, 4, 5])
tensor([2, 4])
tensor([[0.5000, 0.2500],
        [1.0000, 0.5000],
        [1.5000, 0.7500],
        [2.0000, 1.0000],
        [2.5000, 1.2500]])


In [10]:
import torch
from torch.utils.data import Dataset, DataLoader

# 定义自定义的 DataSet 类
class CustomDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sample = self.data[idx]
        return sample

# 创建一些示例数据
data = [[1, 2], [3, 4], [5, 6]]

# 创建自定义的 DataSet 对象
dataset = CustomDataset(data)

# 创建 DataLoader 对象，用于批量加载数据
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# 遍历 DataLoader，获取批量数据
for batch in dataloader:
    print(batch)


[tensor([3, 5]), tensor([4, 6])]
[tensor([1]), tensor([2])]
